## 和Numpy的互操作

In [1]:
import numpy as np
import torch

In [6]:
x = np.array([[1, 2], [3, 4]])
y = torch.from_numpy(x)

In [7]:
x

array([[1, 2],
       [3, 4]])

In [8]:
y

tensor([[1, 2],
        [3, 4]])

In [10]:
x.dtype

dtype('int64')

In [11]:
y.dtype

torch.int64

In [15]:
z = y.numpy()

In [17]:
z

array([[1, 2],
       [3, 4]])

In [16]:
z.dtype

dtype('int64')