In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [6]:
# 并初始化为随机值
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4552, -0.0654,  1.0287],
        [ 0.8232,  0.4353, -0.5158]], requires_grad=True)
tensor([-1.2019,  1.7676], requires_grad=True)


In [7]:
# 定义模型
def model(x):
    return x @ w.t() + b

In [8]:
preds = model(inputs)
print(preds)

tensor([[  5.4200,  68.8429],
        [ 17.4557,  81.9687],
        [ 10.0946, 101.7937],
        [-12.3831,  85.3632],
        [ 33.1192,  64.2461]], grad_fn=<AddBackward0>)


In [9]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [13]:
loss = mse(preds, targets)
print(loss)

tensor(3119.6470, grad_fn=<DivBackward0>)


In [14]:
loss.backward()

In [15]:
# 权重的梯度
print(w)
print(w.grad)

tensor([[-0.4552, -0.0654,  1.0287],
        [ 0.8232,  0.4353, -0.5158]], requires_grad=True)
tensor([[-5455.6968, -6352.2207, -3744.4229],
        [ -675.2483, -1822.1375, -1024.2125]])


In [17]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])
