In [1]:
import tensorflow as tf

In [2]:
# 随机正态分布
W = tf.Variable(initial_value=tf.random.normal(shape=(1,4), mean=100, stddev=0.35), name='W')
b = tf.Variable(tf.zeros([4]), name='b')

In [3]:
# 创建了变量，里面还没有值
[W, b]

[<tf.Variable 'W:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b:0' shape=(4,) dtype=float32_ref>]

## 初始化变量

In [4]:
# 创建会话
sess = tf.Session()
# 初始化全局变量W 和 b
sess.run(tf.global_variables_initializer())
# 执行操作，获取变量值
sess.run([W, b])

[array([[100.160515, 100.41458 , 100.3524  ,  99.562805]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [6]:
# 更新变量值
sess.run(tf.assign_add(b, [1, 2, 3, 4]))

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# 查看变量b 是否更新成功
sess.run(b)

array([1., 2., 3., 4.], dtype=float32)

In [9]:
b.eval(sess)

array([1., 2., 3., 4.], dtype=float32)

<br>

## Saver使用示例
```PYTHON
v1 = tf.Variable(..., name='v1')
v2 = tf.Variable(..., name='v2')
# 指定需要保存和恢复的变量
saver = tf.train.Saver({'v1': v1, 'v2': v2})
saver = tf.train.Saver([v1, v2])
saver = tf.train.Saver({v.op.name: v for v in [v1, v2]})
# 保存变量的方法
# 会话，文件名前缀，指明当前的步数（以后好恢复，像index，前缀的补充）
tf.train.saver.save(sess, 'my-model', global_step=0) # ==> filename: 'my-model-0'
```

In [11]:
# 创建Saver
saver = tf.train.Saver([W, b])
# 存储变量到文件'./summary/test.ckpt-0'
saver.save(sess, './summary/test.ckpt', global_step=0)

'./summary/test.ckpt-0'

In [13]:
# 再次更新b的操作
sess.run(tf.assign_add(b, [1,1,1,1]))
# 查看最新值
sess.run(b)

array([2., 3., 4., 5.], dtype=float32)

In [14]:
# 从文件中恢复变量值
saver.restore(sess, './summary/test.ckpt-0')
# 查看b 是否恢复成功
sess.run(b)

INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


array([1., 2., 3., 4.], dtype=float32)